# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restful.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='restful.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rrestful.proto\x1a google/protobuf/descriptor.proto\"\n\n\x08\x64\x61tetime\"\x06\n\x04\x64\x61te*F\n\x0f\x45numMessageType\x12\t\n\x05MDATA\x10\x00\x12\x08\n\x04MAPI\x10\x01\x12\x08\n\x04MREQ\x10\x02\x12\x08\n\x04MRSP\x10\x03\x12\n\n\x06MQUERY\x10\x04*x\n\x0b\x45numMethods\x12\x08\n\x04MGET\x10\x00\x12\t\n\x05MPOST\x10\x01\x12\x08\n\x04MPUT\x10\x02\x12\x0b\n\x07MDELETE\x10\x03\x12\n\n\x06MPATCH\x10\x04\x12\x0c\n\x08MOPTIONS\x10\x05\x12\t\n\x05MHEAD\x10\x06\x12\x0c\n\x08MCONNECT\x10\x07\x12\n\n\x06MTRACE\x10\x08*>\n\x0c\x45numBodyType\x12\x0e\n\nBURLENCODE\x10\x00\x12\t\n\x05\x42JSON\x10\x01\x12\x08\n\x04\x42XML\x10\x02\x12\t\n\x05\x42YAML\x10\x03:/\n\x04ruri\x12\x1f.google.protobuf.MessageOptions\x18\xa0\xe1g \x01(\t:0\n\x05rpath\x12\x1f.google.protobuf.MessageOptions\x18\xa1\xe1g \x01(\t:@\n\x07rmethod\x12\x1f.google.protobuf.MessageOptions\x18\xa2\xe1g \x01(\x0e\x32\x0c.EnumMethods:?\n\x05rbody\x12\x1f.google.protobuf.MessageOptions\x18\xa3\xe1g \x01(\x0e\x32\r.EnumBodyType:A\n\x04rmsg\x12\x1f.google.protobuf.MessageOptions\x18\xa4\xe1g \x01(\x0e\x32\x10.EnumMessageType:/\n\x06maxlen\x12\x1d.google.protobuf.FieldOptions\x18\x91\xbf\x05 \x01(\x05:/\n\x06minlen\x12\x1d.google.protobuf.FieldOptions\x18\x92\xbf\x05 \x01(\x05:/\n\x06maxval\x12\x1d.google.protobuf.FieldOptions\x18\x93\xbf\x05 \x01(\x02:/\n\x06minval\x12\x1d.google.protobuf.FieldOptions\x18\x94\xbf\x05 \x01(\x02:/\n\x06\x64\x65\x63len\x12\x1d.google.protobuf.FieldOptions\x18\x95\xbf\x05 \x01(\x05:1\n\x08\x64\x65\x63point\x12\x1d.google.protobuf.FieldOptions\x18\x96\xbf\x05 \x01(\x05:,\n\x03key\x12\x1d.google.protobuf.FieldOptions\x18\x97\xbf\x05 \x01(\x08:,\n\x03inc\x12\x1d.google.protobuf.FieldOptions\x18\x98\xbf\x05 \x01(\x08:/\n\x06update\x12\x1d.google.protobuf.FieldOptions\x18\x99\xbf\x05 \x01(\x08:/\n\x06\x64\x65\x66val\x12\x1d.google.protobuf.FieldOptions\x18\xaa\xf7\x36 \x01(\tb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])

_ENUMMESSAGETYPE = _descriptor.EnumDescriptor(
  name='EnumMessageType',
  full_name='EnumMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MDATA', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAPI', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MREQ', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MRSP', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MQUERY', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=71,
  serialized_end=141,
)
_sym_db.RegisterEnumDescriptor(_ENUMMESSAGETYPE)

EnumMessageType = enum_type_wrapper.EnumTypeWrapper(_ENUMMESSAGETYPE)
_ENUMMETHODS = _descriptor.EnumDescriptor(
  name='EnumMethods',
  full_name='EnumMethods',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MGET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MPOST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MPUT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MDELETE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MPATCH', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOPTIONS', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MHEAD', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MCONNECT', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MTRACE', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=143,
  serialized_end=263,
)
_sym_db.RegisterEnumDescriptor(_ENUMMETHODS)

EnumMethods = enum_type_wrapper.EnumTypeWrapper(_ENUMMETHODS)
_ENUMBODYTYPE = _descriptor.EnumDescriptor(
  name='EnumBodyType',
  full_name='EnumBodyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BURLENCODE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BJSON', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BXML', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BYAML', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=265,
  serialized_end=327,
)
_sym_db.RegisterEnumDescriptor(_ENUMBODYTYPE)

EnumBodyType = enum_type_wrapper.EnumTypeWrapper(_ENUMBODYTYPE)
MDATA = 0
MAPI = 1
MREQ = 2
MRSP = 3
MQUERY = 4
MGET = 0
MPOST = 1
MPUT = 2
MDELETE = 3
MPATCH = 4
MOPTIONS = 5
MHEAD = 6
MCONNECT = 7
MTRACE = 8
BURLENCODE = 0
BJSON = 1
BXML = 2
BYAML = 3

RURI_FIELD_NUMBER = 1700000
ruri = _descriptor.FieldDescriptor(
  name='ruri', full_name='ruri', index=0,
  number=1700000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
RPATH_FIELD_NUMBER = 1700001
rpath = _descriptor.FieldDescriptor(
  name='rpath', full_name='rpath', index=1,
  number=1700001, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
RMETHOD_FIELD_NUMBER = 1700002
rmethod = _descriptor.FieldDescriptor(
  name='rmethod', full_name='rmethod', index=2,
  number=1700002, type=14, cpp_type=8, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
RBODY_FIELD_NUMBER = 1700003
rbody = _descriptor.FieldDescriptor(
  name='rbody', full_name='rbody', index=3,
  number=1700003, type=14, cpp_type=8, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
RMSG_FIELD_NUMBER = 1700004
rmsg = _descriptor.FieldDescriptor(
  name='rmsg', full_name='rmsg', index=4,
  number=1700004, type=14, cpp_type=8, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
MAXLEN_FIELD_NUMBER = 90001
maxlen = _descriptor.FieldDescriptor(
  name='maxlen', full_name='maxlen', index=5,
  number=90001, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
MINLEN_FIELD_NUMBER = 90002
minlen = _descriptor.FieldDescriptor(
  name='minlen', full_name='minlen', index=6,
  number=90002, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
MAXVAL_FIELD_NUMBER = 90003
maxval = _descriptor.FieldDescriptor(
  name='maxval', full_name='maxval', index=7,
  number=90003, type=2, cpp_type=6, label=1,
  has_default_value=False, default_value=float(0),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
MINVAL_FIELD_NUMBER = 90004
minval = _descriptor.FieldDescriptor(
  name='minval', full_name='minval', index=8,
  number=90004, type=2, cpp_type=6, label=1,
  has_default_value=False, default_value=float(0),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
DECLEN_FIELD_NUMBER = 90005
declen = _descriptor.FieldDescriptor(
  name='declen', full_name='declen', index=9,
  number=90005, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
DECPOINT_FIELD_NUMBER = 90006
decpoint = _descriptor.FieldDescriptor(
  name='decpoint', full_name='decpoint', index=10,
  number=90006, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
KEY_FIELD_NUMBER = 90007
key = _descriptor.FieldDescriptor(
  name='key', full_name='key', index=11,
  number=90007, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
INC_FIELD_NUMBER = 90008
inc = _descriptor.FieldDescriptor(
  name='inc', full_name='inc', index=12,
  number=90008, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
UPDATE_FIELD_NUMBER = 90009
update = _descriptor.FieldDescriptor(
  name='update', full_name='update', index=13,
  number=90009, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
DEFVAL_FIELD_NUMBER = 900010
defval = _descriptor.FieldDescriptor(
  name='defval', full_name='defval', index=14,
  number=900010, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_DATETIME = _descriptor.Descriptor(
  name='datetime',
  full_name='datetime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=61,
)


_DATE = _descriptor.Descriptor(
  name='date',
  full_name='date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['datetime'] = _DATETIME
DESCRIPTOR.message_types_by_name['date'] = _DATE
DESCRIPTOR.enum_types_by_name['EnumMessageType'] = _ENUMMESSAGETYPE
DESCRIPTOR.enum_types_by_name['EnumMethods'] = _ENUMMETHODS
DESCRIPTOR.enum_types_by_name['EnumBodyType'] = _ENUMBODYTYPE
DESCRIPTOR.extensions_by_name['ruri'] = ruri
DESCRIPTOR.extensions_by_name['rpath'] = rpath
DESCRIPTOR.extensions_by_name['rmethod'] = rmethod
DESCRIPTOR.extensions_by_name['rbody'] = rbody
DESCRIPTOR.extensions_by_name['rmsg'] = rmsg
DESCRIPTOR.extensions_by_name['maxlen'] = maxlen
DESCRIPTOR.extensions_by_name['minlen'] = minlen
DESCRIPTOR.extensions_by_name['maxval'] = maxval
DESCRIPTOR.extensions_by_name['minval'] = minval
DESCRIPTOR.extensions_by_name['declen'] = declen
DESCRIPTOR.extensions_by_name['decpoint'] = decpoint
DESCRIPTOR.extensions_by_name['key'] = key
DESCRIPTOR.extensions_by_name['inc'] = inc
DESCRIPTOR.extensions_by_name['update'] = update
DESCRIPTOR.extensions_by_name['defval'] = defval
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

datetime = _reflection.GeneratedProtocolMessageType('datetime', (_message.Message,), {
  'DESCRIPTOR' : _DATETIME,
  '__module__' : 'restful_pb2'
  # @@protoc_insertion_point(class_scope:datetime)
  })
_sym_db.RegisterMessage(datetime)

date = _reflection.GeneratedProtocolMessageType('date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'restful_pb2'
  # @@protoc_insertion_point(class_scope:date)
  })
_sym_db.RegisterMessage(date)

google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(ruri)
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(rpath)
rmethod.enum_type = _ENUMMETHODS
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(rmethod)
rbody.enum_type = _ENUMBODYTYPE
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(rbody)
rmsg.enum_type = _ENUMMESSAGETYPE
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(rmsg)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(maxlen)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(minlen)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(maxval)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(minval)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(declen)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(decpoint)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(key)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(inc)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(update)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(defval)

# @@protoc_insertion_point(module_scope)
